### ISSUE TITLE
setValue is not handled correctly

### ISSUE THREAD

**Issue by a-schild** [kimppa/FilterableTwinColSelect#1]
I just tried to use it, but have no success with set/get the values.

My basic problem is that it does not show the selected values in the right column when I do a setValue(....)
Replacing the component with the original TwinColSelect and it works as expected....

Looking at your code, it seems to be missing a setValue(...) method handling the two columns

**Comment by kimppa** [comment]
Weird that I have missed that. Thanks for the notification, I'll try to take a look at it as soon as I have some time (that will unfortunately not be within the next couple of weeks).

**Comment by kimppa** [comment]
Airports combined with delayed flights can sometimes mean positive things - I found some time to fix this bug, I'll shortly release a updated version of the add-on in directory.
